<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html>
      <head>
        <title>XML Sitemap - RAC Forge</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body {
            font-family: "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
            color: #1a1a1a;
            background-color: #f8fafc;
            margin: 0;
            padding: 40px 20px;
          }
          .container {
            max-width: 1000px;
            margin: 0 auto;
            background: #fff;
            padding: 40px;
            border-radius: 20px;
            box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1);
          }
          h1 {
            color: #0c2b4b;
            font-size: 32px;
            font-weight: 800;
            margin-bottom: 10px;
            display: flex;
            align-items: center;
          }
          .logo-dot {
            width: 12px;
            height: 12px;
            background-color: #008080;
            border-radius: 50%;
            margin-right: 12px;
          }
          p.description {
            color: #64748b;
            font-size: 16px;
            margin-bottom: 30px;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
          }
          th {
            text-align: left;
            padding: 12px 15px;
            background-color: #f1f5f9;
            color: #475569;
            font-size: 12px;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            font-weight: 700;
            border-bottom: 2px solid #e2e8f0;
          }
          td {
            padding: 12px 15px;
            border-bottom: 1px solid #f1f5f9;
            font-size: 14px;
          }
          tr:hover td {
            background-color: #fdfdfd;
          }
          a {
            color: #008080;
            text-decoration: none;
            font-weight: 500;
          }
          a:hover {
            text-decoration: underline;
          }
          .priority-tag {
            display: inline-block;
            padding: 2px 8px;
            border-radius: 12px;
            font-size: 11px;
            font-weight: 700;
          }
          .priority-high { background-color: #dcfce7; color: #166534; }
          .priority-med { background-color: #fef9c3; color: #854d0e; }
          .priority-low { background-color: #f1f5f9; color: #475569; }
          
          .footer {
            margin-top: 40px;
            text-align: center;
            color: #94a3b8;
            font-size: 12px;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <h1><div class="logo-dot"></div> RAC Forge XML Sitemap</h1>
          <p class="description">
            This XML sitemap is generated by RAC Forge to help search engines discover our content more efficiently.
            It contains <xsl:value-of select="count(//*[local-name()='url'])"/> URLs.
          </p>
          
          <table>
            <thead>
              <tr>
                <th style="text-align: left; padding: 12px 15px;">Location</th>
                <th style="text-align: left; padding: 12px 15px;">Priority</th>
              </tr>
            </thead>
            <tbody>
              <xsl:for-each select="//*[local-name()='url']">
                <tr>
                  <td style="padding: 12px 15px; border-bottom: 1px solid #f1f5f9;">
                    <a href="{*[local-name()='loc']}">
                      <xsl:value-of select="*[local-name()='loc']"/>
                    </a>
                  </td>
                  <td style="padding: 12px 15px; border-bottom: 1px solid #f1f5f9;">
                    <xsl:value-of select="*[local-name()='priority']"/>
                  </td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
          
          <div class="footer">
            © 2026 RAC Forge. All rights reserved.
          </div>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
